#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
#  Bhaisepati Sports Academy — First-time server setup
#  Run this ONCE on the production server (babal.host, rishipa2)
#
#  Usage:
#    chmod +x server-setup.sh
#    bash server-setup.sh
# ═══════════════════════════════════════════════════════════════
set -euo pipefail

# ── Config ────────────────────────────────────────────────────
PROJECT_DIR="$HOME/bsa"
REPO="git@github-bsa:DTYFHTF/bhaisepatisportacademy.git"
NODE_BIN="/opt/alt/alt-nodejs20/root/usr/bin"
NVM_BIN="$HOME/nodevenv/public_applications/20/lib/bin"
export PATH="$NODE_BIN:$NVM_BIN:$PATH"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}→${NC} $*"; }
warn()  { echo -e "${YELLOW}!!${NC} $*"; }
step()  { echo; echo -e "${GREEN}══════════════════════════════════════════${NC}"; echo -e "${GREEN}  $*${NC}"; echo -e "${GREEN}══════════════════════════════════════════${NC}"; }
pause() { echo; warn "$*"; echo "    Press ENTER to continue..."; read -r; }

# ── Step 1: GitHub deploy key ─────────────────────────────────
step "Step 1/5 — GitHub Deploy Key"

if [[ ! -f "$HOME/.ssh/bsa_github" ]]; then
  info "Generating SSH deploy key..."
  ssh-keygen -t ed25519 -f "$HOME/.ssh/bsa_github" -N "" -C "bsa-deploy@babal.host"
else
  info "Deploy key already exists."
fi

# Add SSH config entry for this key
if ! grep -q "Host github-bsa" "$HOME/.ssh/config" 2>/dev/null; then
  info "Adding GitHub SSH config entry..."
  mkdir -p "$HOME/.ssh"
  cat >> "$HOME/.ssh/config" <<'SSHEOF'

Host github-bsa
    HostName github.com
    User git
    IdentityFile ~/.ssh/bsa_github
SSHEOF
fi
chmod 600 "$HOME/.ssh/config"

echo
echo -e "${YELLOW}┌─────────────────────────────────────────────────────────────┐${NC}"
echo -e "${YELLOW}│  Add this deploy key on GitHub — READ ONLY, no write needed  │${NC}"
echo -e "${YELLOW}│  → github.com/DTYFHTF/bhaisepatisportacademy → Settings → Deploy keys  │${NC}"
echo -e "${YELLOW}└─────────────────────────────────────────────────────────────┘${NC}"
echo
cat "$HOME/.ssh/bsa_github.pub"
echo
pause "Copy the key above → add to GitHub → then press ENTER"

# Verify connection
info "Testing GitHub connection..."
ssh -o StrictHostKeyChecking=no -T git@github.com 2>&1 | grep -q "successfully authenticated" \
  && echo -e "${GREEN}✅ GitHub connection OK${NC}" \
  || warn "Could not verify GitHub connection, continuing anyway..."

# ── Step 2: Clone monorepo ────────────────────────────────────
step "Step 2/5 — Clone Monorepo"

if [[ -d "$PROJECT_DIR/.git" ]]; then
  info "Repo already cloned, pulling latest..."
  cd "$PROJECT_DIR"
  GIT_SSH_COMMAND="ssh -i ~/.ssh/bsa_github" git pull origin main
else
  info "Cloning git@github-bsa:DTYFHTF/bhaisepatisportacademy.git..."
  git clone "$REPO" "$PROJECT_DIR"
fi

# ── Step 3: Laravel API ───────────────────────────────────────
step "Step 3/5 — Laravel API Setup"

cd "$PROJECT_DIR/bsa-api"

# Install PHP dependencies
info "Installing Composer dependencies..."
composer install --no-dev --optimize-autoloader --no-progress --quiet

# Set up .env
if [[ ! -f ".env" ]]; then
  cp .env.example .env
  info "Generated .env from .env.example"
fi

# Generate app key if not set
if grep -q "^APP_KEY=$" .env; then
  info "Generating application key..."
  php artisan key:generate
fi

echo
echo -e "${YELLOW}┌─────────────────────────────────────────────────────────────┐${NC}"
echo -e "${YELLOW}│  Fill in these values in .env before continuing:             │${NC}"
echo -e "${YELLOW}│                                                               │${NC}"
echo -e "${YELLOW}│  DB_DATABASE=rishipa2_bsa   ← exact name from cPanel      │${NC}"
echo -e "${YELLOW}│  DB_USERNAME=rishipa2_bsa_user                             │${NC}"
echo -e "${YELLOW}│  DB_PASSWORD=<your-db-password>                               │${NC}"
echo -e "${YELLOW}│  OTP_SECRET=$(openssl rand -hex 32)     ← autogenerated below │${NC}"
echo -e "${YELLOW}│  SPARROW_TOKEN=<your-sparrow-token>                           │${NC}"
echo -e "${YELLOW}│  KHALTI_SECRET=<key>   KHALTI_PUBLIC_KEY=<key>                │${NC}"
echo -e "${YELLOW}│  ESEWA_MERCHANT_CODE=<code>                                   │${NC}"
echo -e "${YELLOW}│  CLOUDINARY_URL=cloudinary://key:secret@dhknx0eac             │${NC}"
echo -e "${YELLOW}│  CLOUDINARY_API_KEY=<key>  CLOUDINARY_API_SECRET=<secret>     │${NC}"
echo -e "${YELLOW}└─────────────────────────────────────────────────────────────┘${NC}"
echo
echo -e "  A fresh OTP_SECRET for you: ${GREEN}$(openssl rand -hex 32)${NC}"
echo
pause "Edit the .env file (run: nano $PROJECT_DIR/bsa-api/.env) then press ENTER"

# Run migrations and seed
info "Running migrations..."
php artisan migrate --force

info "Seeding products..."
php artisan db:seed --class=ProductSeeder

info "Publishing assets..."
php artisan filament:assets
php artisan livewire:publish --assets 2>/dev/null || true
php artisan storage:link --force 2>/dev/null || true

info "Building caches..."
php artisan config:cache
php artisan route:cache
php artisan view:cache
php artisan event:cache

echo -e "${GREEN}✅ API setup complete${NC}"

# ── Step 4: Nuxt Frontend ─────────────────────────────────────
step "Step 4/5 — Nuxt Frontend Build + PM2"

cd "$PROJECT_DIR/bsa-web"

# Make tmp/ for Passenger restart signal
mkdir -p tmp

info "Installing npm dependencies..."
npm ci --quiet

info "Building Nuxt app (this takes ~60s)..."
npm run build

info "Starting PM2..."
pm2 start ecosystem.config.cjs --env production || pm2 reload ecosystem.config.cjs --env production

# Persist PM2 process list
pm2 save

# Try setting up auto-start via cron (no sudo needed)
if ! crontab -l 2>/dev/null | grep -q "pm2 resurrect"; then
  (crontab -l 2>/dev/null; echo "@reboot export PATH=$NODE_BIN:$NVM_BIN:\$PATH && pm2 resurrect") | crontab -
  info "Added PM2 resurrect to crontab (auto-start on reboot)"
fi

echo -e "${GREEN}✅ Frontend built and PM2 started on port 3001${NC}"

# ── Step 5: Summary ───────────────────────────────────────────
step "Step 5/5 — cPanel Manual Steps"

echo
echo -e "  ${YELLOW}Two things still need to be done in cPanel:${NC}"
echo
echo -e "  ${GREEN}A) API subdomain${NC}"
echo -e "     cPanel → Subdomains → Create Subdomain"
echo -e "     Subdomain:     api"
echo -e "     Domain:        bsa.example.com"
echo -e "     Document Root: bsa/bsa-api/public"
echo
echo -e "  ${GREEN}B) Node.js app for bsa.example.com${NC}"
echo -e "     cPanel → Setup Node.js App → Create Application"
echo -e "     Node.js version:   20"
echo -e "     Application mode:  Production"
echo -e "     Application root:  bsa/bsa-web"
echo -e "     Application URL:   bsa.example.com"
echo -e "     Startup file:      .output/server/index.mjs"
echo -e "     ↑ This creates the .htaccess proxy to port 3001"
echo
echo -e "  ${GREEN}C) GitHub Actions secrets${NC}"
echo -e "     github.com/DTYFHTF/bhaisepatisportacademy → Settings → Secrets → Actions"
echo
echo -e "     VPS_HOST     = 192.250.235.21"
echo -e "     VPS_USER     = rishipa2"
echo -e "     VPS_PORT     = 22"
echo -e "     VPS_SSH_KEY  = (paste your local ~/.ssh/id_ed25519 private key)"
echo
echo -e "     NUXT_PUBLIC_GOOGLE_MAPS_KEY = (your restricted Google Maps key)"
echo
echo -e "${GREEN}════════════════════════════════════════════${NC}"
echo -e "${GREEN}  🚀  Setup complete! Visit https://bsa.example.com${NC}"
echo -e "${GREEN}════════════════════════════════════════════${NC}"
